---
- name: Configure Group Accounts RDP to Supporting Servers (SRV)
  hosts:
    - t1srv
    #- g1srv
    #- g2srv
    #- g3srv
    #- g4srv
    #- g5srv
  gather_facts: yes

  tasks:
    - name: Add members to the remote desktop users group and local administrators group
      ansible.windows.win_group_membership:
        name: Remote Desktop Users
        members: group1,group2,group3,group4,group5
        state: present
    
    - name: Add users to the remote desktop users group and local administrators group
      ansible.windows.win_group_membership:
        name: Administrators
        members: group1,group2,group3,group4,group5
        state: present

